version: "3.8"

services:
  math-agent:
    build: .
    container_name: math-agent
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./vectorstore/math_db:/app/vectorstore/math_db
      - ./feedback_data:/app/feedback_data
    command: /start.sh